// let aaalll = document.querySelector(".JsAll");
// let baataa = document.querySelector(".JsBata");
// let puuuma = document.querySelector(".JsPima");
// let niiike = document.querySelector(".JsNike");
// let guucci = document.querySelector(".JsGucci");

// let one = document.querySelector("#one");
// let two = document.querySelector("#two");
// let three = document.querySelector("#three");
// let four = document.querySelector("#four");
// let five = document.querySelector("#five");
// let six = document.querySelector("#six");
// let seven = document.querySelector("#seven");
// let eight = document.querySelector("#eight");
// let nine = document.querySelector("#nine");
// let ten = document.querySelector("#ten");
// let eleven = document.querySelector("#eleven");
// let twelve = document.querySelector("#twelve");
// let thirteen = document.querySelector("#thirteen");
// let fourteen = document.querySelector("#fourteen");
// let fifteen = document.querySelector("#fifteen");
// let sixteen = document.querySelector("#sixteen");

// aaalll.addEventListener("click", function(){
//     aaalll.classList.add("active");
//     baataa.classList.remove("active");
//     puuuma.classList.remove("active");
//     niiike.classList.remove("active");
//     guucci.classList.remove("active");

//     one.classList.add("rotateAll");
//     two.classList.add("rotateAll");
//     three.classList.add("rotateAll");
//     four.classList.add("rotateAll");

//     five.classList.add("rotateAll");
//     six.classList.add("rotateAll");
//     seven.classList.add("rotateAll");
//     eight.classList.add("rotateAll");

//     nine.classList.add("rotateAll");
//     ten.classList.add("rotateAll");
//     eleven.classList.add("rotateAll");
//     twelve.classList.add("rotateAll");

//     thirteen.classList.add("rotateAll");
//     fourteen.classList.add("rotateAll");
//     fifteen.classList.add("rotateAll");
//     sixteen.classList.add("rotateAll");


//     one.style.display = "block";
//     two.style.display = "block";
//     three.style.display = "block";
//     four.style.display = "block";

//     five.style.display = "block";
//     six.style.display = "block";
//     seven.style.display = "block";
//     eight.style.display = "block";

//     nine.style.display = "block";
//     ten.style.display = "block";
//     eleven.style.display = "block";
//     twelve.style.display = "block";

//     thirteen.style.display = "block";
//     fourteen.style.display = "block";
//     fifteen.style.display = "block";
//     sixteen.style.display = "block";
// });

// baataa.addEventListener("click", function(){
//     aaalll.classList.remove("active");
//     baataa.classList.add("active");
//     puuuma.classList.remove("active");
//     niiike.classList.remove("active");
//     guucci.classList.remove("active");

//     thirteen.style.display = "block";
//     fourteen.style.display = "block";
//     fifteen.style.display = "block";
//     sixteen.style.display = "block";

//     //animation
//     one.classList.remove("rotate");
//     two.classList.remove("rotate");
//     three.classList.remove("rotate");
//     four.classList.remove("rotate");

//     five.classList.remove("rotate");
//     six.classList.remove("rotate");
//     seven.classList.remove("rotate");
//     eight.classList.remove("rotate");

//     nine.classList.remove("rotate");
//     ten.classList.remove("rotate");
//     eleven.classList.remove("rotate");
//     twelve.classList.remove("rotate");

//     thirteen.classList.add("rotate");
//     fourteen.classList.add("rotate");
//     fifteen.classList.add("rotate");
//     sixteen.classList.add("rotate");


//     one.classList.remove("rotateAll");
//     two.classList.remove("rotateAll");
//     three.classList.remove("rotateAll");
//     four.classList.remove("rotateAll");

//     five.classList.remove("rotateAll");
//     six.classList.remove("rotateAll");
//     seven.classList.remove("rotateAll");
//     eight.classList.remove("rotateAll");

//     nine.classList.remove("rotateAll");
//     ten.classList.remove("rotateAll");
//     eleven.classList.remove("rotateAll");
//     twelve.classList.remove("rotateAll");

//     thirteen.classList.remove("rotateAll");
//     fourteen.classList.remove("rotateAll");
//     fifteen.classList.remove("rotateAll");
//     sixteen.classList.remove("rotateAll");
//     //animation


//     one.style.display = "none";
//     two.style.display = "none";
//     three.style.display = "none";
//     four.style.display = "none";
//     five.style.display = "none";
//     six.style.display = "none";
//     seven.style.display = "none";
//     eight.style.display = "none";
//     nine.style.display = "none";
//     ten.style.display = "none";
//     eleven.style.display = "none";
//     twelve.style.display = "none";
// });

// puuuma.addEventListener("click", function(){
//     aaalll.classList.remove("active");
//     baataa.classList.remove("active");
//     puuuma.classList.add("active");
//     niiike.classList.remove("active");
//     guucci.classList.remove("active");

  

    

//     one.classList.add("rotate");
//     two.classList.add("rotate");
//     three.classList.add("rotate");
//     four.classList.add("rotate");

//     five.classList.remove("rotate");
//     six.classList.remove("rotate");
//     seven.classList.remove("rotate");
//     eight.classList.remove("rotate");

//     nine.classList.remove("rotate");
//     ten.classList.remove("rotate");
//     eleven.classList.remove("rotate");
//     twelve.classList.remove("rotate");

//     thirteen.classList.remove("rotate");
//     fourteen.classList.remove("rotate");
//     fifteen.classList.remove("rotate");
//     sixteen.classList.remove("rotate");

//     one.classList.remove("rotateAll");
//     two.classList.remove("rotateAll");
//     three.classList.remove("rotateAll");
//     four.classList.remove("rotateAll");

//     five.classList.remove("rotateAll");
//     six.classList.remove("rotateAll");
//     seven.classList.remove("rotateAll");
//     eight.classList.remove("rotateAll");

//     nine.classList.remove("rotateAll");
//     ten.classList.remove("rotateAll");
//     eleven.classList.remove("rotateAll");
//     twelve.classList.remove("rotateAll");

//     thirteen.classList.remove("rotateAll");
//     fourteen.classList.remove("rotateAll");
//     fifteen.classList.remove("rotateAll");
//     sixteen.classList.remove("rotateAll");



//     one.style.display = "block";
//     two.style.display = "block";
//     three.style.display = "block";
//     four.style.display = "block";

//     five.style.display = "none";
//     six.style.display = "none";
//     seven.style.display = "none";
//     eight.style.display = "none";

//     nine.style.display = "none";
//     ten.style.display = "none";
//     eleven.style.display = "none";
//     twelve.style.display = "none";

//     thirteen.style.display = "none";
//     fourteen.style.display = "none";
//     fifteen.style.display = "none";
//     sixteen.style.display = "none";
// });

// niiike.addEventListener("click", function(){
//     aaalll.classList.remove("active");
//     baataa.classList.remove("active");
//     puuuma.classList.remove("active");
//     niiike.classList.add("active");
//     guucci.classList.remove("active");


    
//     one.classList.remove("rotate");
//     two.classList.remove("rotate");
//     three.classList.remove("rotate");
//     four.classList.remove("rotate");

//     five.classList.add("rotate");
//     six.classList.add("rotate");
//     seven.classList.add("rotate");
//     eight.classList.add("rotate");

//     nine.classList.remove("rotate");
//     ten.classList.remove("rotate");
//     eleven.classList.remove("rotate");
//     twelve.classList.remove("rotate");

//     thirteen.classList.remove("rotate");
//     fourteen.classList.remove("rotate");
//     fifteen.classList.remove("rotate");
//     sixteen.classList.remove("rotate");

//     one.classList.remove("rotateAll");
//     two.classList.remove("rotateAll");
//     three.classList.remove("rotateAll");
//     four.classList.remove("rotateAll");

//     five.classList.remove("rotateAll");
//     six.classList.remove("rotateAll");
//     seven.classList.remove("rotateAll");
//     eight.classList.remove("rotateAll");

//     nine.classList.remove("rotateAll");
//     ten.classList.remove("rotateAll");
//     eleven.classList.remove("rotateAll");
//     twelve.classList.remove("rotateAll");

//     thirteen.classList.remove("rotateAll");
//     fourteen.classList.remove("rotateAll");
//     fifteen.classList.remove("rotateAll");
//     sixteen.classList.remove("rotateAll");


//     one.style.display = "none";
//     two.style.display = "none";
//     three.style.display = "none";
//     four.style.display = "none";

//     five.style.display = "block";
//     six.style.display = "block";
//     seven.style.display = "block";
//     eight.style.display = "block";

//     nine.style.display = "none";
//     ten.style.display = "none";
//     eleven.style.display = "none";
//     twelve.style.display = "none";

//     thirteen.style.display = "none";
//     fourteen.style.display = "none";
//     fifteen.style.display = "none";
//     sixteen.style.display = "none";
// });

// guucci.addEventListener("click", function(){
//     aaalll.classList.remove("active");
//     baataa.classList.remove("active");
//     puuuma.classList.remove("active");
//     niiike.classList.remove("active");
//     guucci.classList.add("active");

//     one.classList.remove("rotate");
//     two.classList.remove("rotate");
//     three.classList.remove("rotate");
//     four.classList.remove("rotate");

//     five.classList.remove("rotate");
//     six.classList.remove("rotate");
//     seven.classList.remove("rotate");
//     eight.classList.remove("rotate");

//     nine.classList.add("rotate");
//     ten.classList.add("rotate");
//     eleven.classList.add("rotate");
//     twelve.classList.add("rotate");

//     thirteen.classList.remove("rotate");
//     fourteen.classList.remove("rotate");
//     fifteen.classList.remove("rotate");
//     sixteen.classList.remove("rotate");

//     one.classList.remove("rotateAll");
//     two.classList.remove("rotateAll");
//     three.classList.remove("rotateAll");
//     four.classList.remove("rotateAll");

//     five.classList.remove("rotateAll");
//     six.classList.remove("rotateAll");
//     seven.classList.remove("rotateAll");
//     eight.classList.remove("rotateAll");

//     nine.classList.remove("rotateAll");
//     ten.classList.remove("rotateAll");
//     eleven.classList.remove("rotateAll");
//     twelve.classList.remove("rotateAll");

//     thirteen.classList.remove("rotateAll");
//     fourteen.classList.remove("rotateAll");
//     fifteen.classList.remove("rotateAll");
//     sixteen.classList.remove("rotateAll");


//     one.style.display = "none";
//     two.style.display = "none";
//     three.style.display = "none";
//     four.style.display = "none";

//     five.style.display = "none";
//     six.style.display = "none";
//     seven.style.display = "none";
//     eight.style.display = "none";

//     nine.style.display = "block";
//     ten.style.display = "block";
//     eleven.style.display = "block";
//     twelve.style.display = "block";

//     thirteen.style.display = "none";
//     fourteen.style.display = "none";
//     fifteen.style.display = "none";
//     sixteen.style.display = "none";

// });


//jQuery......>

// $(function(){
//     let heading = $('.test');

//     heading.on("click", function(){
//         $(this).hide();
//     });

//     let addBorder = $(".border");
//     let removeBorder = $(".remove");

//     let show = $(".show");
//     let hide = $(".hide");
//     let toggle = $(".toggle");

//     let box = $(".box");

//     addBorder.on("click", function(){
//         box.css({
//             border: "5px solid red"
            
//         });
//         addBorder.css({
//             display: "none"
//         });
//         removeBorder.css({
//             display: "inline-block"
//         });
//     });

//     removeBorder.on("click", function(){
//         removeBorder.css({
//             display: "none"
//         });
//         addBorder.css({
//             display: "inline-block"
//         });

//         box.css({
//             border: "5px solid green"
//         });
//     });

//     show.on("click", function(){
//         box.slideDown();
//     });

//     hide.on("click", function(){
//         box.slideUp();
//     });

//     toggle.on("click", function(){
//         box.slideToggle();
//     });

   



// });


// $(function(){
//     let refresh = $(".ref")
//     let start = $(".start");
//     let stop = $(".stop");

//     let box_two = $(".box_two");

//     refresh.on("click", function(){
//         box_two.animate({
//             width: '1%'
//         })
//     })


//     start.on("click", function(){
//          box_two.animate({
//              width: '100%'
//          },5000);
//     });

//     stop.on("click", function(){
//         box_two.stop();
//     });


// });

// $(function(){
//     let question = $(".question");
//     let answer = $(".answer");

//     let span = $('span');
//     let iii = $("i");



//     question.on("click", function(){
//         answer.slideToggle()

      
//     });

//     let question_two = $(".question_two");
//     let answer_two = $(".answer_two");

//     question_two.on("click", function(){
//         answer_two.slideToggle()
//     });

//     let question_three = $(".question_three");
//     let answer_three = $(".answer_three");

//     question_three.on("click", function(){
//         answer_three.slideToggle()
//     });
// });

// $(function(){
//     $('.slick_parent').slick({
//         infinite: true,
//         slidesToShow:  3,
//         slidesToScroll: 3,
//         prevArrow: '<span class="left" onclick="audio.play();"> <i class="fa-solid fa-arrow-left"></i> </span>',
//         nextArrow: '<span class="right" onclick="audio.play();"> <i class="fa-solid fa-arrow-right"></i> </span>',

//         centerMode: true,
//         centerPadding: '0px',
//     });

//     new VenoBox({
//         selector: '.my-video-links',
//     });

// });

// let firstCard = document.querySelector("#first_card");
// let secondCard = document.querySelector("#second_card");
// let thirdCard = document.querySelector("#third_card");

// window.addEventListener('scroll', function(){
//     let test = this.document.documentElement.scrollTop;
//     if(test > 1300){
//         firstCard.classList.add("first");
//     }
//     else{
//         firstCard.classList.remove("first");
//     }
// });

    const audio = new Audio();
    audio.src = "boom.unknown";


let show = document.querySelector("#show");
let hide = document.querySelector("#hide");
let input = document.querySelector("input");

show.addEventListener("click", function(){
    input.type = "text";
    show.style.display = "none";
    hide.style.display = "block";
});
hide.addEventListener("click", function(){
    input.type = "password";
    show.style.display = "block";
    hide.style.display = "none";
});

$(function(){
    let Mode = $(".mode");
    let modeClick = $("#mode_click");

    Mode.on("click", function(){
        modeClick.css.display = "block"
        modeClick.slideToggle();
    })
});

let White = document.querySelector("#white");
let Green = document.querySelector("#green");
let Black = document.querySelector("#black");

let modeClick = document.querySelector("#mode_click");
let Body = document.querySelector("body");

let heading = document.querySelector("#h1");
let heading_two = document.querySelector("#h2");
let heading_three = document.querySelector("#h3");
let heading_four = document.querySelector("#h4");


White.addEventListener("click", function(){
    Body.style.background = "white";
    White.style.scale = "1.1";
    Green.style.scale = "1";
    Black.style.scale = "1";
    White.style.background = "rgb(0, 255, 47)";
    Green.style.background = "white";
    Black.style.background = "white";

    modeClick.style.display = "none"

    heading.style.color = "brown";
    heading_two.style.color = "brown";

    Black.style.border = "0"
    Green.style.border = "0"
    White.style.border = "2px solid"
});
Green.addEventListener("click", function(){
    Body.style.background = "rgb(0, 255, 47)";
    White.style.scale = "1";
    Green.style.scale = "1.1";
    Black.style.scale = "1";
    Green.style.background = "rgb(0, 255, 47)";
    White.style.color = "black";
    White.style.background = "white";
    Black.style.color = "black";

    heading.style.color = "rgb(0, 0, 0)";
    heading_two.style.color = "rgb(0, 0, 0)";

    modeClick.style.display = "none"

    Black.style.border = "0"
    Green.style.border = "2px solid"
    White.style.border = "0";

    heading_three.style.color = "black";
    heading_four.style.color = "black";
});

Black.addEventListener("click", function(){
    Body.style.background = "black";
    White.style.scale = "1";
    Green.style.scale = "1";
    Black.style.scale = "1.1"
    Green.style.background = "white";
    White.style.background = "white";
    Black.style.background = "rgb(0, 255, 47)";
    heading.style.color = "rgb(255, 187, 0)";
    heading_two.style.color = "rgb(255, 187, 0)";

    modeClick.style.display = "none";

    Black.style.border = "2px solid"
    Green.style.border = "0"
    White.style.border = "0"

    heading_three.style.color = "rgb(255, 187, 0)";
    heading_four.style.color = "rgb(255, 187, 0)";
    
});

let colorBox = document.querySelector(".color_box");



colorBox.addEventListener("click", function(){
    RED = Math.floor(Math.random()*255);
    GREEN = Math.floor(Math.random()*255);
    BLUE = Math.floor(Math.random()*255);
    colorBox.style.background = `rgb(${RED}, ${GREEN}, ${BLUE})`;
});


const Command = document.querySelector(".exeCommand");  
const passwordBox = document.querySelector("#password");
const length = 12;

// const upperCase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
// const lowerCase = "abcdefghijklmnopqrstuvwxyz";
// const numbers = "0123456789";
// const symbol = "!@#$%^&*()_-+={]:;.<,?/\~`";

//const everyCharacter = upperCase + lowerCase + numbers + symbol;
const everyCharacter = "!@#$%^&*()_-+=ABCDEFGHIabcdefghijklmnopqrstuvwxyzJKLMNOPQRSTUVWXYZ>0123456789{]:;.~`<,?/";

function creatPassword(){
    let password = "";

    // password += upperCase[Math.floor(Math.random()*upperCase.length)];
    // password += lowerCase[Math.floor(Math.random()*lowerCase.length)];
    // password += numbers[Math.floor(Math.random()*numbers.length)];
    // password += symbol[Math.floor(Math.random()*symbol.length)];
    password += everyCharacter[Math.floor(Math.random()*everyCharacter.length)];

    while(length > password.length){
        password += everyCharacter[Math.floor(Math.random()*everyCharacter.length)];

        passwordBox.value = password;
    };

    Command.style.display = "none";

    const audio = new Audio();
    audio.src = "boom.unknown";
};
 
function copyCode(){
    passwordBox.select();
    document.execCommand("copy");

    Command.style.display = "block";
};



//sticky nav


let slideBody = document.querySelector("body");
let navBar = document.querySelector("#scroll");
window.addEventListener("scroll", function(){
   
    let test = document.documentElement.scrollTop;
    if(test > 100){
        navBar.classList.add("scroll_active");
        
    }else{
        navBar.classList.remove("scroll_active");
       
    }
});




let setting = document.querySelector("#setting");
let sidebar = document.querySelector("#sidebar");
let cross = document.querySelector("#cross");

let parentSlidar = document.querySelector(".parent_slidar")


setting.addEventListener("click", () => {
    sidebar.style.display = "block";
    sidebar.classList.add("try");
    parentSlidar.style.display = "block";
});
parentSlidar.addEventListener("click", () => {
    sidebar.style.display = "none";
    parentSlidar.style.display = "none";
});
cross.addEventListener("click", () => {
    sidebar.style.display = "none";
});
